version: '3.8'

services:
  backend:
    build:
      context: ./backend  
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - 3000:3000
      - 5555:5555 # Port used by Prisma Studio
    working_dir: /app/backend

  database:
    image: postgis/postgis
    restart: on-failure
    env_file:
      - docker.env
    ports:
      - "5432:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresql-data:      