version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: ./backend  
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    ports:
      - 3000:3000
      - 5555:5555 # Port used by Prisma Studio
    working_dir: /app/backend
    depends_on:
      - database

  database:
    container_name: database
    image: postgis/postgis
    restart: on-failure
    env_file:
      - docker.env
    ports:
      - "5433:5432"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgresql-data:/var/lib/postgresql/data
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
    ports:
      - 5173:5173
    working_dir: /app/frontend
    depends_on:
      - backend
      - database

  adminer:
    container_name: adminer
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgresql-data:      