name: Deploy production

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  buildNDeploy:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses:
          actions/checkout@v4

          ##DEPLOY CLIENT
      - name: Build, Push and Release a client app container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_CLIENT }}

          dockerfile_directory: ./frontend

          dockerfile_name: Dockerfile.prod

          # Additional options of docker build command.
          docker_options: '--no-cache'

          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          process_type: web

        ##DEPLOY SERVER
      - name: Build, Push and Release a server container to Heroku.
        uses: gonuit/heroku-docker-deploy@v1.3.3
        with:
          # The email address associated with your Heroku account.
          email: ${{ secrets.HEROKU_EMAIL }}

          # Heroku API key associated with provided user's email.
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}

          # Name of the heroku application to which the build is to be sent.
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_SERVER }}

          dockerfile_directory: ./backend

          dockerfile_name: Dockerfile.prod

          # Additional options of docker build command.
          docker_options: '--no-cache'

          # Select the process type for which you want the docker container to be uploaded.
          # By default, this argument is set to "web".
          process_type: web
